Add Okta integration docs
arcionlabs/arcion-docs pull request #2
Opened 2023-06-21 07:41 UTC by lstracak92

2023-06-21 11:52 UTC, selectiveduplicate requested changes

2023-06-21 11:52 UTC, selectiveduplicate commented on content/docs/security/okta.md
> +description: "Authenticate your replicant users by using Okta integration."
We should capitalize "Replicant" everywhere. 
I think we can remove the word "integration" here as an attributive.

2023-06-21 11:52 UTC, selectiveduplicate commented on content/docs/security/okta.md
> +# Setting up Okta as an authentication provider
Since these are all task-based headings, I suggest we use imperatives like this:

> Set up Okta as an authentication provider

2023-06-21 11:52 UTC, selectiveduplicate commented on content/docs/security/okta.md
> +Self-hosted replicant supports Okta integration as an authentication provider. In order to set it up, the following is required:
> Self-hosted Replicant supports Okta as an authentication provider.

2023-06-21 11:52 UTC, selectiveduplicate commented on content/docs/security/okta.md
> +* A valid Okta account
Let's move these "requirements" under a separate section like this:

## Requirements
- A valid Okta account
- A Replicant self-hosted docker container
- A database for Replicant container metadata

2023-06-21 11:52 UTC, selectiveduplicate commented on content/docs/security/okta.md
> +For the sake of simplicity we'll be using a basic container and Okta configuration.
I'm not sure this line is necessary here.

2023-06-21 11:52 UTC, selectiveduplicate commented on content/docs/security/okta.md
> +## Setting up your Okta account
I think **Create an Okta Application** would be more suitable heading here.

2023-06-21 11:52 UTC, selectiveduplicate commented on content/docs/security/okta.md
> +
We need to write these in a series of numbered steps and describe the UI elements better:

1. Log into your Okta account
2. In the Admin Console, go to **Applications > Applications** .
3. Click Create App Integration.
4. Select **OIDC - OpenID Connect** as the **Sign-in method**.
5. Select **Single-Page Application** as the **Application type**.
6. The **New Single-Page App Integration** window appears.
     i. Select both **Authorization Code** and **Refresh Token** as the **Grant type**s. The login process requires **Authorization Code** and the re-authentication mechanism requires **Refresh Token**.
     ii. Enter `http://localhost:8080/auth-callback/` in the **Sign-in redirect URIs** box. We run the container on our local machine without any additional setup. Since the port maps to 8080, the base URL becomes `http://localhost:8080` and the complete **Sign-in redirect URI** becomes `http://localhost:8080/auth-callback/`.
    iii. In the **Sign-out redirect URIs** box, enter the base URL. In this case, it's `http://localhost:8080/`.
    iv. For **Assignments**, select **Allow everyone in your organization to access** . Keep in mind that you can set up user assignments in any way that allows the configured application to authenticate users.

After creating the app integration connection, a window appears with all the details of your application. The **Client Credentials** section contains your application's **Client ID**. This works as your app's public identifier and required by all OAuth flows. Therefore, make sure to save the client ID for later.

With these steps, I think we can remove the two images.

2023-06-21 11:52 UTC, selectiveduplicate commented on content/docs/security/okta.md
> +A Docker-compose file which spins up a PostgreSQL container and a replicant-on-premises container can be found below. Please note that the
> The following Docker compose file spins up a PostgreSQL container and a Replicant on-premises container. Make sure to enter the corresponding credentials and variables for your setup into the Compose file before you use it.

You can get YAML highlighting by using three backticks followed by the name of the snippet language `YAML` (letter casing doesn't matter) like this:

\```YAML
Your snippet goes here
\```

2023-06-21 11:52 UTC, selectiveduplicate commented on content/docs/security/okta.md
> +
An introductory sentence before starting to explain a preceding code snippet or sample:

> In the preceding Compose file, notice the following:

2023-06-21 11:52 UTC, selectiveduplicate commented on content/docs/security/okta.md
> +`CLIENT_ID` Client id from the previous step which is generated when app integration is created</br>
<blockquote>

- `ARCION_LICENSE` specifies the base64 encoded Replicant license.
- `AUTHENTICATION_TYPE` specifies the authentication protocol. Since we're using OIDC/OAuth2 as our authentication protocol, set this parameter to `OAUTH2`.
- `CLIENT_ID` specifies the client id of the corresponding Okta application you create in the [Create an Okta Application](#create-an-okta-application) section.
</blockqoute>

2023-06-21 11:52 UTC, selectiveduplicate commented on content/docs/security/okta.md
> +Okta URIs can be found in the OIDC Discovery configuration file, which by default is located at;
You can find Okta URIs in the OIDC Discovery configuration file. Default location for this file takes the form `https://YOUR_Okta_DOMAIN.okta.com/.well-known/openid-configuration`, where `YOUR_Okta_DOMAIN` represents [your Okta domain](https://developer.okta.com/docs/guides/find-your-domain/main/#find-your-okta-domain). 

For more information on OIDC Discovery, see [OpenID Connect & OAuth 2.0 API](https://developer.okta.com/docs/reference/api/oidc/#well-known-openid-configuration).

2023-06-21 11:52 UTC, selectiveduplicate commented on content/docs/security/okta.md
> +`ISSUER_URI` URI of the authentication issuer (https://trial-12345678.okta.com)</br>
Let's follow the same way we explained the Compose file if we're explaining different URIs.

2023-06-21 11:52 UTC, selectiveduplicate commented on content/docs/security/okta.md
> +Scopes required for client registration are `offline_access openid profile email`
Client registration requires the following scopes:
- `offline_access` 
- `openid` 
- `profile` 
- `email`

2023-06-21 11:52 UTC, selectiveduplicate commented on content/docs/security/okta.md
> +pageTitle: Okta authentication setup
I think "Integrate Okta with Arcion Replicant" sounds better for SEO.

2023-06-21 14:08 UTC, lstracak92 commented on content/docs/security/okta.md
> +Okta URIs can be found in the OIDC Discovery configuration file, which by default is located at;
Okta domain is equal to ${okta_org_name}.okta.com so I've edited the docs to reflect this.

2023-06-21 14:09 UTC, lstracak commented on content/docs/security/okta.md
> +`ISSUER_URI` URI of the authentication issuer (https://trial-12345678.okta.com)</br>
I've moved this to 3rd leave headings and added `Environment variables` section to better represent these values.

2023-06-22 08:42 UTC, selectiveduplicate approved these changes

2023-06-22 08:45 UTC, merged