SI-370 Prometheus metrics endpoint documentation
arcionlabs/arcion-docs pull request #23
Opened 2023-09-18 08:57 UTC by IvoMajic

2023-09-18 15:11 UTC, robert-s-lee commented
wanted a step by step instructions to test each layer so that we can verify 
1. UI works, 
1. then prometheus works, 
1. then grafana works

## ui: 

- make sure ui is setup as a prometheus end point

is there a way treat the ui as a prometheus endpoint and pull the data directly as a test?  for example, http://ui:8050/prometheus/metrics did not return values from the browser.   

## prometheus: 

- connect to http://prometheus:9090 and see the metrics from the prometheus directly

## grafana
 
- connect to prometheus
- configure arcion dashboard

2023-09-18 15:25 UTC, robert-s-lee commented on content/docs/arcion-on-premises-ui/prometheus.md
> +        Replicant:
`Replicant` project name is assumed here. otherwise, an error will be thrown.  using `default` could make better out of the box experience

```
    networks:
      default:
        aliases:
          - grafana 
```

2023-09-18 15:26 UTC, robert-s-lee commented on content/docs/arcion-on-premises-ui/prometheus.md
> +      image: prom/prometheus
what is the version of prometheus that was tested with for a production deployment

2023-09-18 15:30 UTC, robert-s-lee commented on content/docs/arcion-on-premises-ui/prometheus.md
> +    extra_hosts:
container name  `Replicant-on-premises` and network alias name such as `replicant` can be used  without using the `extra_host`.  the reason to prefer `extra_host` and use local loopback is so that prometheus UI would work when displaying targets

2023-09-18 16:04 UTC, robert-s-lee commented
currently, prometheus metrics are emitted for replicated that are kicked off from UI.  replications started from CLI currently do not generate prometheus metrics. 

the prometheus metrics are generated while the replication is running.  stopped, paused, terminated jobs will not emit metrics. 

when snapshot or real-time is running, pointing browser to arcion ui's prometheus endpoint http://localhost:8050/prometheus/  results in the following.  

```
# HELP snapshot_avg_rows_per_sec Average rows per second insert in snapshot phase
# TYPE snapshot_avg_rows_per_sec gauge
snapshot_avg_rows_per_sec{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",current_phase="SNAPSHOT",} 0.0 1695052577647
# HELP avg_rows_per_sec Average rows per second rate
# TYPE avg_rows_per_sec gauge
avg_rows_per_sec{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",current_phase="SNAPSHOT",} 1657519.428286 1695052577647
# HELP active_threads Number of active threads
# TYPE active_threads gauge
active_threads{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",current_phase="SNAPSHOT",} 0.0 1695052577647
# HELP rows_per_sec Total rows per second
# TYPE rows_per_sec gauge
rows_per_sec{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",current_phase="SNAPSHOT",} 1439050.0 1695052577647
# HELP transactions Transactions count
# TYPE transactions gauge
transactions{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",current_phase="SNAPSHOT",} 0.0 1695052577647
# HELP max_memory Maximum memory replicants JVM will attempt to use
# TYPE max_memory gauge
max_memory{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",current_phase="SNAPSHOT",} 2.863136768E10 1695052577647
# HELP total_rows Total rows count in target db
# TYPE total_rows gauge
total_rows{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",current_phase="SNAPSHOT",} 1.1604634E7 1695052577647
# HELP sample_count Number of metric computations - CDC resets this to 0
# TYPE sample_count gauge
sample_count{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",current_phase="SNAPSHOT",} 8.0 1695052577647
# HELP tables_created Tables created count
# TYPE tables_created gauge
tables_created{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",current_phase="SNAPSHOT",} 14.0 1695052577647
# HELP buffered_operations Buffered operations count
# TYPE buffered_operations gauge
buffered_operations{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",current_phase="SNAPSHOT",} 0.0 1695052577647
# HELP snapshot_total_rows Total rows count either hinted by user and then corrected by replicant at the end of snapshot or count otherwise
# TYPE snapshot_total_rows gauge
snapshot_total_rows{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",current_phase="SNAPSHOT",} 1.1604635E7 1695052577647
# HELP free_memory Memory available for replicant to use
# TYPE free_memory gauge
free_memory{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",current_phase="SNAPSHOT",} 9.25772E8 1695052577647
# HELP failed_transactions Failed transactions count
# TYPE failed_transactions gauge
failed_transactions{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",current_phase="SNAPSHOT",} 0.0 1695052577647
# HELP peak_rows_per_sec Peak rows per second rate
# TYPE peak_rows_per_sec gauge
peak_rows_per_sec{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",current_phase="SNAPSHOT",} 2165584.0 1695052577647
# HELP tables_dropped Tables dropped count
# TYPE tables_dropped gauge
tables_dropped{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",current_phase="SNAPSHOT",} 0.0 1695052577647
# HELP total_memory Total memory allocated to replicants JVM
# TYPE total_memory gauge
total_memory{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",current_phase="SNAPSHOT",} 1.005060096E9 1695052577647
# HELP buffered_transactions Buffered transactions count
# TYPE buffered_transactions gauge
buffered_transactions{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",current_phase="SNAPSHOT",} 0.0 1695052577647
# HELP total_lag Time difference between commit to source and commit to target
# TYPE total_lag gauge
total_lag{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",current_phase="SNAPSHOT",} 9.223372036854776E18 1695052577647
# HELP replication_lag Time difference between extracting query and committing to target
# TYPE replication_lag gauge
replication_lag{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",current_phase="SNAPSHOT",} 9.223372036854776E18 1695052577647
# HELP table_rows Rows count
# TYPE table_rows gauge
table_rows{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",table="arcsrc_default_schema_warehouse",} 1.0 1695052577647
# HELP table_snapshot_rows Total rows in snapshot
# TYPE table_snapshot_rows gauge
table_snapshot_rows{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",table="arcsrc_default_schema_warehouse",} 1.0 1695052577647
# HELP table_inserted_rows Inserted rows count
# TYPE table_inserted_rows gauge
table_inserted_rows{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",table="arcsrc_default_schema_warehouse",} 1.0 1695052577647
# HELP table_truncate_operations Truncate operations count
# TYPE table_truncate_operations gauge
table_truncate_operations{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",table="arcsrc_default_schema_warehouse",} 0.0 1695052577647
# HELP table_replaced_rows Replaced rows count
# TYPE table_replaced_rows gauge
table_replaced_rows{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",table="arcsrc_default_schema_warehouse",} 0.0 1695052577647
# HELP table_ddl DDL operations count
# TYPE table_ddl gauge
table_ddl{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",table="arcsrc_default_schema_warehouse",} 0.0 1695052577647
# HELP table_affected_rows Rows affected by this replication
# TYPE table_affected_rows gauge
table_affected_rows{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",table="arcsrc_default_schema_warehouse",} 1.0 1695052577647
# HELP table_updated_rows Updated rows count
# TYPE table_updated_rows gauge
table_updated_rows{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",table="arcsrc_default_schema_warehouse",} 0.0 1695052577647
# HELP table_lag Time difference between query on source and commit to destination
# TYPE table_lag gauge
table_lag{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",table="arcsrc_default_schema_warehouse",} 9.223372036854776E18 1695052577647
# HELP table_buffered_operations Buffered operations for labeled table
# TYPE table_buffered_operations gauge
table_buffered_operations{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",table="arcsrc_default_schema_warehouse",} 0.0 1695052577647
# HELP table_rows_per_sec Rows per second rate
# TYPE table_rows_per_sec gauge
table_rows_per_sec{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",table="arcsrc_default_schema_warehouse",} 0.0 1695052577647
# HELP table_replication_lag Time difference between extracting query and committing to target
# TYPE table_replication_lag gauge
table_replication_lag{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",table="arcsrc_default_schema_warehouse",} 9.223372036854776E18 1695052577647
# HELP table_rows_estimate_size Total rows count either hinted by user and then corrected by replicant at the end of snapshot or count otherwise
# TYPE table_rows_estimate_size gauge
table_rows_estimate_size{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",table="arcsrc_default_schema_warehouse",} 1.0 1695052577647
# HELP table_deleted_rows Deleted rows count
# TYPE table_deleted_rows gauge
table_deleted_rows{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",table="arcsrc_default_schema_warehouse",} 0.0 1695052577647
# HELP table_rows Rows count
# TYPE table_rows gauge
table_rows{replication_id="ac120006-8aa8-1654-818a-a8f46ccd0000",table="arcsrc_default_schema_history",} 30000.0 1695052577647
# HELP table_snapshot_rows Total rows in snapshot
# TYPE table_snapshot_rows gauge
table_snapshot_rows{replication_id="ac120006-8aa8-1654-818a-a8f46ccd [...]

2023-09-18 17:48 UTC, robert-s-lee commented on content/docs/arcion-on-premises-ui/prometheus.md
> +          - '<YOUR_INTERNAL_PATH>/prometheus.yaml:/etc/prometheus/prometheus.yaml'
/etc/prometheus/prometheus.yml is the default file that needs to be overridden and NOT .yaml file.

2023-09-18 19:50 UTC, robert-s-lee commented on content/files/Arcion_Replication_Dashboard.json
make the following display changes to make the numbers have K,M,B suffix
1. Total Rows: change the unit to `short`
1. Peak rows per second: change the unit to `short`
1. Snapshot total rows: change the unit to `short`
1. active threads: change the unit to `short`
1. average rows per second: change the unit to `short`

make graphs with a lot of tables a heatmap that makes easier to see which table is hot
1. rows per second
2. buffered operations
3. log
4. affected rows per table
make rows per second heatmap

2023-09-19 09:39 UTC, selectiveduplicate requested changes

2023-09-19 09:39 UTC, selectiveduplicate commented on content/docs/arcion-on-premises-ui/prometheus.md
> +Self-hosted Replicant supports exposing a Prometheus metrics data endpoint.
Shouldn't we say _Arcion On-premises UI_?

I suggest we add more text about some overview about our integration. Feel free to suggest more details if there are any:

_Arcion On-premises UI exposes a [Prometheus](https://prometheus.io/) metrics data endpoint. This allows you to use Prometheus and Grafana to collect and visualize metrics about your ongoing replications. Our Prometheus integration collects metrics from configured targets at given intervals and displays the results._

2023-09-19 09:39 UTC, selectiveduplicate commented on content/docs/arcion-on-premises-ui/prometheus.md
> +title: Prometheus monitoring
I suggest _integration_.

2023-09-19 09:39 UTC, selectiveduplicate commented on content/docs/arcion-on-premises-ui/prometheus.md
> +pageTitle: Integrate Premetheus with Arcion Replicant to monitor running replications
_Integrate Premetheus with Arcion On-premises UI_.

`pageTitle` can't be too long.

2023-09-19 09:39 UTC, selectiveduplicate commented on content/docs/arcion-on-premises-ui/prometheus.md
> +description: "Use Prometheus to monitor running replications."
_Learn how to integrate Prometheus with Arcion On-premises UI to monitor ongoing replications._

2023-09-19 09:39 UTC, selectiveduplicate commented on content/docs/arcion-on-premises-ui/prometheus.md
> +- A running instance of Prometheus server to scrape the data
_A running instance of Prometheus server to scrape the data. To set up a working instance, follow the instructions in [Prometheus installation docs](https://prometheus.io/docs/prometheus/latest/installation/)._

2023-09-19 09:39 UTC, selectiveduplicate commented on content/docs/arcion-on-premises-ui/prometheus.md
> +- A Replicant self-hosted docker container
_An Arcion On-premises UI Docker container._

2023-09-19 09:39 UTC, selectiveduplicate commented on content/docs/arcion-on-premises-ui/prometheus.md
> +- (Optional) A instance of your data visualisation tool of choice (in this example Grafana)
_Optionally, an instance of a data visualization tool of your choice. This example uses Grafana._

2023-09-19 09:39 UTC, selectiveduplicate commented on content/docs/arcion-on-premises-ui/prometheus.md
> +- A database for Replicant container metadata
Let's end with a period.

2023-09-19 09:39 UTC, selectiveduplicate commented on content/docs/arcion-on-premises-ui/prometheus.md
> +The following Docker compose file spins up a Prometheus server, a Grafana instance, a PostgreSQL container and a Replicant on-premises container. Make sure to enter the corresponding credentials and
_Arcion On-premises container_.
Add a comma after _a PostgreSQL container_.

2023-09-19 09:39 UTC, selectiveduplicate commented on content/docs/arcion-on-premises-ui/prometheus.md
> +In the preceding Compose file, notice the following environment variables:
Since we talk about one environment variable, no need to use a list. Let's say it like the following:

_In the preceding Compose file,  the `PROMETHEUS_ENABLE` environment variable enables or disables Prometheus endpoint._

2023-09-19 09:39 UTC, selectiveduplicate commented on content/docs/arcion-on-premises-ui/prometheus.md
> +By default the Prometheus metrics endpoint is exposed on port 8050. The metrics endpoint path is: `http://localhost:8050/prometheus/metrics`
I'm assuming the Compose file dictates the port. Otherwise, feel free to replace with the appropriate subject. The main goal is to avoid passive voice and use a succinct sentence.

_By default, the preceding configuration exposes the Prometheus metrics endpoint at `http://localhost:8050/prometheus/metrics` on port 8050._

2023-09-19 09:39 UTC, selectiveduplicate commented on content/docs/arcion-on-premises-ui/prometheus.md
> +- access the Prometheus server at `http://localhost:9090` and configure the metrics endpoint as a target. Here is an example of a `prometheus.yaml` scraping configuration:
Let's capitalize first word of each list item.

_The following example shows a `prometheus.yaml` scraping configuration:_

2023-09-19 09:39 UTC, selectiveduplicate commented on content/docs/arcion-on-premises-ui/prometheus.md
> +```
The code block isn't rendering properly as a part of the list item. You might have to indent the code block by two or four spaces from the list item.

2023-09-19 09:39 UTC, selectiveduplicate commented on content/docs/arcion-on-premises-ui/prometheus.md
> +- login into Grafana (`http://localhost:9090`, default username/password is `admin/admin`) and setup the Prometheus server as a Datasource (`https://grafana.com/docs/grafana/latest/datasources/promet
We can split this into two list items:

- Log into Grafana at `http://localhost:9090`. The default username and password for Grafana are `admin` and `admin`.
- [Set up the Prometheus server as a data source for Grafana](https://grafana.com/docs/grafana/latest/datasources/prometheus/configure-prometheus-data-source/). 

We always use proper link text and not just the URL on its own. There exists exceptions—for example, the first list item in the preceding list.

2023-09-19 09:39 UTC, selectiveduplicate commented on content/docs/arcion-on-premises-ui/prometheus.md
> +- you can create your own Dashboard or use our example Dashboard that you can download [here](/files/Arcion_Replication_Dashboard.json).
For the link text, let's use our example dashboard_ instead of _here_. Remove _that you can download here_.
We don't need to capitalize _dashboard_ since it's not part of a product name; the Grafana and Prometheus docs themselves don't capitalize _dashboard_.

2023-09-19 10:30 UTC, anasY2 commented on content/docs/arcion-on-premises-ui/prometheus.md
> +pageTitle: Integrate Premetheus with Arcion Replicant to monitor running replications
Just a spelling mistake. It should be _Prometheus_  not _Premetheus_.

2023-09-19 18:02 UTC, robert-s-lee commented on content/docs/arcion-on-premises-ui/prometheus.md
> +- login into Grafana (`http://localhost:9090`, default username/password is `admin/admin`) and setup the Prometheus server as a Datasource (`https://grafana.com/docs/grafana/latest/datasources/promet
Grafana source and dashboard setup took some time to figure out.  I would suggest providing an example that matches the provided docker compose file would be helpful.

- setup data source
  - click on `Add your first data source`
  - click on `Prometheus`
  - in the Prometheus form
    - name field: `arcion`
    - URL field: `http://localhost:8050`
    - click `Save and Test` button
    - click on `Data sources` at the top
 - From the left navigation panel, click on Dashboard
   - click on `New` pulldown menu
   - click on `Import`
   - click on `Upload dashboard json file`
   - select the download json dashboard
   - in the json form
     - from the prometheus drop down, select arcion
     - click import

2023-09-19 19:28 UTC, robert-s-lee commented
providing 
- a sample screenshot
- json file that has a heatmap which works better with multiple tables and K,M,B suffix on large numbers
<img width="864" alt="Screenshot 2023-09-19 at 3 07 47 PM" src="https://github.com/arcionlabs/arcion-docs/assets/6315124/b227a68a-2ad6-42ed-b9b2-889d33f1c7de">

[Arcion Replication Dashboard-1695149301732.json.zip](https://github.com/arcionlabs/arcion-docs/files/12665758/Arcion.Replication.Dashboard-1695149301732.json.zip)

2023-09-20 06:07 UTC, selectiveduplicate commented
> providing
> 
> * a sample screenshot

If we're providing a screenshot of the dashboard, I suggest taking one of _just_ the dashboard in full screen. In Chrome, you can go full screen by pressing F11. This hides the top browser panels.

2023-09-20 23:48 UTC, IvoMajic commented on content/docs/arcion-on-premises-ui/prometheus.md
> +- login into Grafana (`http://localhost:9090`, default username/password is `admin/admin`) and setup the Prometheus server as a Datasource (`https://grafana.com/docs/grafana/latest/datasources/promet
We linked the Grafana source setup docs for Prometheus, I am not sure we should go this specific here as the Grafana UI might change

2023-09-21 09:08 UTC, selectiveduplicate requested changes
Couple of points to address. Otherwise, looks good.

2023-09-21 09:08 UTC, selectiveduplicate commented on content/docs/arcion-on-premises-ui/prometheus.md
> +## Configure Arcion On-premises UI container to expose the Prometheus endpoint
I suggest shortening the heading a bit:

_Configure Arcion On-premises UI to expose Prometheus endpoint_

2023-09-21 09:08 UTC, selectiveduplicate commented on content/docs/arcion-on-premises-ui/prometheus.md
> +### Usage
I don't think **Usage** belongs as a child heading of **Configure Arcion On-premises UI to expose Prometheus endpoint**. So let's put **Usage** as an H2 heading instead.

2023-09-21 09:08 UTC, selectiveduplicate commented on content/docs/arcion-on-premises-ui/prometheus.md
> +- Make sure you have setup a **running replication** in the UI. Navigate to `http://localhost:8050/prometheus/metrics` and you should see the metrics output in your browser.
For better understanding, I suggest we split the list items and put them into two child H3 headings under **Usage**. 

## Usage
### Prometheus
...the points about using Prometheus....

### Grafana
... the last three points about using Grafana...

2023-09-21 09:08 UTC, selectiveduplicate commented on content/docs/arcion-on-premises-ui/prometheus.md
> +  After starting Prometheus with this configuration file, open `http://localhost:9090` in your browser and confirm the server is properly scraping the data (under Status > Targets).
_After starting Prometheus with the preceding configuration, open `http://localhost:9090` in your browser. To make sure that Prometheus properly scrapes the data, select **Targets** in the **Status** menu from the top menu bar. The **Targets** page displays important scrape-related information for all active targets:_

2023-09-21 09:08 UTC, selectiveduplicate commented on content/docs/arcion-on-premises-ui/prometheus.md
> +  ![Prometheus](/images/prometheus.png)
Let's use a more descriptive alt text:

_Prometheus targets page showing the scrape endpoint, endpoint state, labels associated with the target, scrape time and duration, and scrape error._

2023-09-21 09:08 UTC, selectiveduplicate commented on content/docs/arcion-on-premises-ui/prometheus.md
> +  ![Grafana](/images/grafana_dashboard.png)
Better alt text:

_A Grafana dashboard showing various replication statistics for an ongoing replication._

2023-09-28 08:41 UTC, merged