contribute.md spell check and hugo setup on dev branch
arcionlabs/arcion-docs pull request #3
Opened 2023-07-07 14:32 UTC by robert-s-lee

- spell check
- instruction to install hugo
- instructions start hugo w/ dev branch

2023-07-10 06:33 UTC, selectiveduplicate requested changes

2023-07-10 06:33 UTC, selectiveduplicate commented on CONTRIBUTING.md
> +# Tools Setup
Set up Hugo

2023-07-10 06:33 UTC, selectiveduplicate commented on CONTRIBUTING.md
> +This section helps you set up the tools you'll need to write the docs.
This section helps you set up Hugo on your machine so that you can run the website and verify your changes locally.

2023-07-10 06:33 UTC, selectiveduplicate commented on CONTRIBUTING.md
> +These instructions assume that you use `ubuntu`. If you use other distributions of Linux, please make appropriate adjustments.
These instructions apply to Ubuntu. For other Linux distributions, see the [Hugo Linux installation docs](https://gohugo.io/installation/linux/).

2023-07-10 06:33 UTC, selectiveduplicate commented on CONTRIBUTING.md
> +- Install Hugo
Let's end each introductory sentence with a colon and use numbered steps instead.

Our theme actually recommends using Hugo extended, with version 0.79 or higher. I don't think all releases of Ubuntu repositories provide such newer versions. So the recommended approach to install Hugo is to grab the appropriate prebuilt binary from the [Hugo releases page](https://github.com/gohugoio/hugo/releases). I think we should write the steps that way.

2023-07-10 06:33 UTC, selectiveduplicate commented on CONTRIBUTING.md
> +- Start Hugo
2. Go inside your `arcion-docs` repository:
    ```sh
    cd arcion-docs/
   ```

3. Start Hugo server:

2023-07-10 06:33 UTC, selectiveduplicate commented on CONTRIBUTING.md
> +
`hugo server` builds the website and serves it using an HTTP server. After you run `hugo server`, it displays the URL of the local build:

```
Web Server is available at //localhost:1313/ (bind address 127.0.0.1)
```

You can make changes while the server is running. The server automatically detects any change you make in website content and and rebuilds the site.

2023-07-10 06:33 UTC, selectiveduplicate commented on CONTRIBUTING.md
> +- [Tools Setup](#tools-setup)
- [Set up Hugo](#set-up-hugo)

2023-07-12 20:24 UTC, robert-s-lee commented
@selectiveduplicate please check

2023-07-13 06:05 UTC, selectiveduplicate requested changes
Looks good. One minor edit and we're good to go!

2023-07-13 06:05 UTC, selectiveduplicate commented on CONTRIBUTING.md
> +  For these cases, the recommended approach to install Hugo is to grab the appropriate prebuilt binary from the Hugo releases page.
Let's hyperlink to the Hugo releases page: https://github.com/gohugoio/hugo/releases.

2023-07-13 11:27 UTC, robert-s-lee commented on CONTRIBUTING.md
> +  For these cases, the recommended approach to install Hugo is to grab the appropriate prebuilt binary from the Hugo releases page.
done

2023-07-13 15:35 UTC, selectiveduplicate approved these changes

2023-07-13 15:37 UTC, merged